name = "svelte-parking"
main = "worker.js"
compatibility_date = "2025-07-23"

[build]
command = "sed -i \"s/GIT_COMMIT/$(git rev-parse --short HEAD)/\" public/index.html"

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
PARKING_API_URL = "https://statsmon-api.azurewebsites.net/parkingAvailability"
ROUTE_PREFIX = "/parking"
